/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.skillforge;

/**
 *
 * @author User
 */
public class Insructor extends javax.swing.JFrame {
    Instructor instructor = (Instructor).getCurrentUser();
    /**
     * Creates new form Insructor
     */
    public Insructor() {
        initComponents();
        LoadCreatedCourses();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        InstructorName = new javax.swing.JLabel();
        InstructorId = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        EnrolledStudentBtn = new javax.swing.JButton();
        ViewLessonsBtn = new javax.swing.JButton();
        CreateNewCourseBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        RemoveCourseBtn = new javax.swing.JButton();
        AddLessonBtn = new javax.swing.JButton();
        RemoveLessonBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        CourseTable = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        LessonsTable = new javax.swing.JTable();
        SaveBtn = new javax.swing.JButton();
        CourseSaveBtn1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InstructorName.setText("e");

        InstructorId.setText("jLabel7");

        jLabel1.setText("Created Courses");

        EnrolledStudentBtn.setText("View Enrolled Students");
        EnrolledStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnrolledStudentBtnActionPerformed(evt);
            }
        });

        ViewLessonsBtn.setText("View Lessons");
        ViewLessonsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewLessonsBtnActionPerformed(evt);
            }
        });

        CreateNewCourseBtn.setText("Create New Course");
        CreateNewCourseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateNewCourseBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Related Lessons ");

        RemoveCourseBtn.setText("Remove Course");
        RemoveCourseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveCourseBtnActionPerformed(evt);
            }
        });

        AddLessonBtn.setText("Add Lesson");
        AddLessonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddLessonBtnActionPerformed(evt);
            }
        });

        RemoveLessonBtn.setText("Remove Lesson");
        RemoveLessonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveLessonBtnActionPerformed(evt);
            }
        });

        CourseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Title", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        CourseTable.setColumnSelectionAllowed(true);
        CourseTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(CourseTable);
        CourseTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        LessonsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Title", "Content", "optional resources"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(LessonsTable);

        SaveBtn.setText("Save Changes");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        CourseSaveBtn1.setText("Save Changes");
        CourseSaveBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CourseSaveBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(InstructorName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(InstructorId, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AddLessonBtn)
                                    .addComponent(EnrolledStudentBtn)
                                    .addComponent(RemoveLessonBtn)
                                    .addComponent(SaveBtn)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CourseSaveBtn1)
                                            .addComponent(ViewLessonsBtn))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RemoveCourseBtn)
                            .addComponent(CreateNewCourseBtn))
                        .addGap(61, 61, 61))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(InstructorName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InstructorId)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CreateNewCourseBtn)
                            .addComponent(EnrolledStudentBtn))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ViewLessonsBtn)
                            .addComponent(RemoveCourseBtn))
                        .addGap(42, 42, 42)
                        .addComponent(CourseSaveBtn1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(AddLessonBtn)
                        .addGap(27, 27, 27)
                        .addComponent(RemoveLessonBtn)
                        .addGap(31, 31, 31)
                        .addComponent(SaveBtn)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void LoadCreatedCourses() {
        
    }
    private void EnrolledStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnrolledStudentBtnActionPerformed
       
    }//GEN-LAST:event_EnrolledStudentBtnActionPerformed

    private void CreateNewCourseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateNewCourseBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateNewCourseBtnActionPerformed

    private void RemoveCourseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveCourseBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RemoveCourseBtnActionPerformed

    private void ViewLessonsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewLessonsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewLessonsBtnActionPerformed

    private void AddLessonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddLessonBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddLessonBtnActionPerformed

    private void RemoveLessonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveLessonBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RemoveLessonBtnActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void CourseSaveBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CourseSaveBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CourseSaveBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Insructor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Insructor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Insructor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Insructor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Insructor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddLessonBtn;
    private javax.swing.JButton CourseSaveBtn1;
    private javax.swing.JTable CourseTable;
    private javax.swing.JButton CreateNewCourseBtn;
    private javax.swing.JButton EnrolledStudentBtn;
    private javax.swing.JLabel InstructorId;
    private javax.swing.JLabel InstructorName;
    private javax.swing.JTable LessonsTable;
    private javax.swing.JButton RemoveCourseBtn;
    private javax.swing.JButton RemoveLessonBtn;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JButton ViewLessonsBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
